name: Build Installers

on:
  push:
    branches: [ "workflow/installers" ]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore and build (no publish yet)
        run: dotnet build --configuration Release

  # Windows Build
  build-windows-installer:
    needs: build-app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish self-contained for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained true -o publish/win

      - name: Test Windows binary
        run: |
          cd publish/win
          ./EscapeProjectComposition.exe --help

      - name: Create Windows installer script
        run: |
          @"
          @echo off
          echo ==^> Installing Escape Project...
          echo (no dependencies required on Windows)

          echo.
          echo ✅ Installation complete!
          echo To run the program, execute:
          echo   EscapeProjectComposition.exe --help
          echo.
          pause
          "@ | Out-File -FilePath publish/win/install-escape.bat -Encoding ascii

      - name: Bundle Windows build + script
        run: powershell Compress-Archive -Path publish/win/* -DestinationPath windows-installer.zip

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: windows-installer.zip

  # Linux Build
  build-linux-installer:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install native deps (libgdiplus + appimagetool)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdiplus libfuse2 || sudo apt-get install -y libgdiplus libfuse2t64
          wget -O appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/

      - name: Publish self-contained for Linux
        run: dotnet publish -c Release -r linux-x64 --self-contained true -o publish/linux

      - name: Package as AppImage
        run: |
          mkdir -p AppDir/usr/bin
          cp -r publish/linux/* AppDir/usr/bin/
          find /usr/lib -name "libgdiplus.so*" -exec cp {} AppDir/usr/bin/ \; || true
          ln -s /lib/x86_64-linux-gnu/libdl.so.2 AppDir/usr/bin/libdl.so || true
          echo '#!/bin/sh
          HERE=$(dirname "$(readlink -f "$0")")
          exec "$HERE/usr/bin/EscapeProjectComposition" "$@"' > AppDir/AppRun
          chmod +x AppDir/AppRun
          echo '[Desktop Entry]
          Name=Escape Project
          Exec=EscapeProjectComposition
          Icon=escape-project
          Type=Application
          Categories=Utility;' > AppDir/escape-project.desktop
          touch AppDir/escape-project.png
          appimagetool --appimage-extract
          ./squashfs-root/AppRun AppDir EscapeProject-x86_64.AppImage

      - name: Create Linux installer script
        run: |
          cat << 'EOF' > install-escape.sh
          #!/bin/bash
          set -e
          echo "==> Installing required system libraries..."
          if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y libgdiplus libfuse2 || sudo apt-get install -y libgdiplus libfuse2t64
          elif command -v yum >/dev/null 2>&1; then
            sudo yum install -y libgdiplus fuse
          elif command -v pacman >/dev/null 2>&1; then
            sudo pacman -Sy --noconfirm libgdiplus fuse2
          else
            echo "Unsupported Linux distribution. Please install libgdiplus and fuse manually."
            exit 1
          fi
          echo "✅ Dependencies installed."
          echo "Now you can run: ./EscapeProject-x86_64.AppImage"
          EOF
          chmod +x install-escape.sh

      - name: Test Linux AppImage
        run: |
          chmod +x EscapeProject-x86_64.AppImage
          ./EscapeProject-x86_64.AppImage --help

      - name: Bundle Linux AppImage + script
        run: zip linux-installer.zip EscapeProject-x86_64.AppImage install-escape.sh

      - name: Upload Linux installer bundle
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: linux-installer.zip
